name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      # Lista os arquivos na raiz do repositório após o checkout
      - name: List files after checkout
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      # Adicione temporariamente este passo para verificar a estrutura de diretórios
      - name: List all files to verify structure
        run: ls -la ./qax

      - name: Install dependencies
        working-directory: ./qax
        run: yarn install

      - name: Install Cypress
        working-directory: ./qax
        run: yarn add cypress@12.2.0

      - name: Verify Cypress installation
        working-directory: ./qax
        run: yarn cypress verify

      - name: List files in directory
        working-directory: ./qax
        run: ls -la

      - name: Run Cypress tests
        working-directory: ./qax
        run: yarn cypress run --headless
